# QEMU conf file for my kernel

# machine type
[machine]
    type = "q35"

[memory]
    size = "128M"

[smp-opts]
    cpus = "1"

[device "achi0"]
driver = "ich9-ahci"
id = "achi0"

[drive "disk0"]
    file = "./disk.img"
    if = "none"
    format = "raw"
    id = "disk0"

[device "disk0-dev"]
driver = "ide-hd"
drive = "disk0"
bus = "achi0.0"

[drive "cd0"]
file = "./JakelynnOS.iso"
if = "none"
media = "cdrom"
id = "cd0"

[device "cd0-dev"]
driver = "ide-cd"
drive = "cd0"
bus = "achi0.1"

# Define the USB
[device "usb3"]
driver = "qemu-xhci"
id = "usb3"

# Define the Host Network Backend (User-mode/NAT)
[netdev "net0"]
  type = "user"

# Define the Guest Virtual Network Card (Frontend)
[device "nic0"]
  driver = "virtio-net-pci"
  netdev = "net0"
  mac = "52:54:00:12:34:56"